on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  lumberjackKeyboard:
    runs-on: ubuntu-latest
    name: lumberjack
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache qmk toolchain
        uses: actions/cache@v3
        env:
          cache-name: qmk-toolchain
        with:
          path: |
            /home/runner/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies for qmk build
        uses: mstksg/get-package@v1
        with:
          apt-get: git python3-pip dfu-util dfu-programmer avrdude 
      - name: Install qmk using pip
        working-directory: ./qmk_firmware
        run: |
          python3 -m pip install --user qmk
          qmk setup --yes --home .
      - name: Prepare qmk_firmware folder
        run: cp -R lumberjack/ qmk_firmware/keyboards/
      - name: Build cost_crafter36-keyboard firmware
        working-directory: ./qmk_firmware
        run: qmk compile -kb lumberjack -km default 
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: lumberjack-keyboard
          path: qmk_firmware/lumberjack_default.uf2
